language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  
before_script:
  - composer self-update
  - composer install --dev

script:
  - bin/phpunit --coverage-text --exclude-group system
  - bin/php-cs-fixer fix --dry-run --diff -vv

notifications:
  email:
    - travis@b-zik.de

# HHVM precise builds are broken
dist: trusty
