language: php
php:
  - 7.4
  - 8.0

before_script:
  - sudo apt-get install -y gearman-job-server
  - composer install --ignore-platform-reqs

script:
  - vendor/bin/phpunit --coverage-text --verbose
  - vendor/bin/php-cs-fixer fix --dry-run --diff -vv

sudo: true
dist: focal

notifications:
  email:
    - travis@b-zik.de


